# Configuration file for TravisCI
os: linux
dist: xenial
language: python
python: "3.6"
notifications:
  email: false

# Only build pushes from the master branch. PRs are always built.
branches:
  only:
    - master

env:
  global:
    # Doctr deploy key for pinga-lab/pinga-lab.github.io
    - secure: "Kj83Ut0ivN2FWeA7KHF8p3Wgu0Iy4+om0Xy6Uz3+QGQdVkHLHnRI7e5fluGC33LQ0DArtEeFHM5PwrB9oFT50DR/9ldSIkZPL70nJdnOr8IYK6TlxatiZDoCkeDGQDEoYYSTCZMnMokJJdR9HfrW66oppaT7WfyN18BtvfDzH4k="

# Setup the build environment
install:
  # Install the requirements
  - pip install -r requirements.txt

script:
  # Build the website HTML
  - make

deploy:
  # Push the built HMTL to Github pages
  - provider: script
    script: doctr deploy . --built-docs _build --key-path .github_deploy_key.enc --deploy-repo pinga-lab/pinga-lab.github.io
    skip_cleanup: true
    on:
      branch: master
