language: python
before_install:
- cd pelican-plugins; git submodule init; git submodule update; cd ..;
install:
- sudo apt-get update
- sudo apt-get install nodejs
- pip install pelican==3.5.0 markdown==2.4 ipython==2.3.1 pillow beautifulsoup4==4.3.2
script:
- make publish
after_success:
- bash .update-website.sh
env:
  global:
    secure: jzcxV3nJ4VuPZr1tzhrV8NXeo3CZfUJlmU96xhsIXeZ89Ncu0J+yPqfBy6xmk5EDGzCEGYkJkLULm3gAHIodqK8BGGZpvjBVXWoNu+a8eqqIXYI0BKXVEydkusW4oofH041QdGSbmju6nL8UFnhtLwZhfbWJ2YcKI5IONl0yv6w=
