language: python

sudo: false

env:
  global: # For deploying the site to Github Pages
    - secure: jzcxV3nJ4VuPZr1tzhrV8NXeo3CZfUJlmU96xhsIXeZ89Ncu0J+yPqfBy6xmk5EDGzCEGYkJkLULm3gAHIodqK8BGGZpvjBVXWoNu+a8eqqIXYI0BKXVEydkusW4oofH041QdGSbmju6nL8UFnhtLwZhfbWJ2YcKI5IONl0yv6w=
  matrix:
    - PYTHON=2.7

before_install:
  # Get Miniconda from Continuum
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  # Initialize the Pelican plugins submodule
  - cd pelican-plugins; git submodule init; git submodule update; cd ..;

install:
  - conda create -n testenv --yes pip python=$PYTHON
  - conda update conda --yes
  - source activate testenv
  - pip install -r requirements.txt

script:
  - make publish

after_success:
  - bash ci-tools/deploy-gh-pages.sh
